server:
  port: 8080
#编码格式
server.tomcat.uri-encoding: utf-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/classroom?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  type-aliases-package: mybatis.demo.entity
  mapper-locations: classpath:mybatis/security02/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

web:
  upload-path: E://javaee/Classroom/File/

my:
  uploadFolder: E://javaee/Classroom/File/
  previewPath: http://127.0.0.1:8080/image/
